name: Build js
on: pull_request

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present

  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: -c .eslintrc.js --ext .js --fix admin/src/ includes/src/


  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment to use the desired version of NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Installing NPM dependencies
        run: npm install

      - name: Starting the WordPress Environment
        run: npm run wp-env:start

      - name: Running the tests
        run: npm run test:e2e
